version: '3.8'

services:
    django_gunicorn:
        volumes:
        - static:/static
        build:
            context: .
        ports:
        - "8000:8000"
        depends_on:
        - db
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - SECRET_KEY='c*48+8)np*$4ohvxr38x=)(w4vw3!shqm*+m+%v$uzn!q@wk%+'
        - SHARED_DATA_USER_PASSWORD='password'
        - DEBUG=True
        - DJANGO_ENVIRONMENT=production
    nginx:
        build: ./devops/nginx
        volumes:
        - static:/static
        ports:
        - "80:80"
        depends_on:
        - django_gunicorn
    db:
        image: postgres
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
volumes:
    static:
