# This file contains development-specific overrides for docker-compose.base.yml
# It should be used in conjunction with the base configuration file

services:
  django_gunicorn:
    image: ${GUNICORN_IMAGE}:dev
    volumes:
      - static:/static
      - /Users/Development/PycharmProjects/project_working_area/plan_visualiser_2023_02/local_docker_build:/app
    env_file:
      - ../env/.env.dev

  nginx:
    image: ${NGINX_IMAGE}:dev
    volumes:
      - static:/static
    env_file:
      - ../env/.env.dev

  db:
    image: ${POSTGRES_IMAGE}:dev
    env_file:
    - ../env/.env.dev
