version: '3.8'
# ============================================================================
# = Compose file to be run on remote server (Staging or Production)          =
# = after images have been re-built, typically by Github actions.            =
# ============================================================================
services:
  django_gunicorn:
    image: ${DO_DOCKER_REGISTRY_NAME}/planvisualiser/gunicorn:${DOCKER_IMAGE_TAG}
    volumes:
      - static:/static

    ports:
    - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ENVIRONMENT=${DJANGO_ENVIRONMENT}
      - SHARED_USER_NAME=${SHARED_USER_NAME}
      - SHARED_USER_PASSWORD=${SHARED_USER_PASSWORD}
      - APP_USER_1_NAME=${APP_USER_1_NAME}
      - APP_USER_1_PASSWORD=${APP_USER_1_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - INITIAL_USER_EMAIL_DOMAIN=${INITIAL_USER_EMAIL_DOMAIN}
      - EMAIL_HOST
      - EMAIL_USE_SSL
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_PORT
  nginx:
    image: ${DO_DOCKER_REGISTRY_NAME}/planvisualiser/nginx:${DOCKER_IMAGE_TAG}
    volumes:
      - /var/www/app_root/ssl:/etc/nginx/ssl
      - static:/static
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - django_gunicorn
    environment:
      - DJANGO_ENVIRONMENT=${DJANGO_ENVIRONMENT}
  db:
    image: postgres
    environment:
      - "POSTGRES_DB=${POSTGRES_DB_NAME}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
    - data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  static:
  data:
