# Generated by Django 4.2.1 on 2023-06-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0017_alter_planactivity_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="swimlaneforvisual",
            options={"ordering": ["plan_visual", "sequence_number"]},
        ),
    ]
