# Generated by Django 4.2.1 on 2023-06-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0018_alter_swimlaneforvisual_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualactivity",
            name="text_flow",
            field=models.CharField(
                choices=[
                    ("LFLOW", "Align right, flow to left"),
                    ("RFLOW", "Align left, flow to right"),
                    ("WSHAPE", "Align centre, flow left/right"),
                    ("CLIPPED", "Align ce_(ntre, clipped to shape"),
                ],
                max_length=20,
            ),
        ),
    ]
