# Generated by Django 4.2.1 on 2023-06-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0020_alter_planfield_field_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotablestyle",
            name="font_color",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plotablestyle_font",
                to="plan_visual_django.color",
            ),
            preserve_default=False,
        ),
    ]
