# Generated by Django 4.2.1 on 2023-07-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0023_alter_planmappedfield_input_field_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotableshapetype",
            name="name",
            field=models.CharField(
                choices=[("RECTANGLE", "Rectangle"), ("DIAMOND", "Diamond")],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TimelineLabelsForVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_type",
                    models.CharField(
                        choices=[
                            ("MONTHS", "One label for each month"),
                            (
                                "QUARTERS",
                                "One label for each sequence of three months, variable start",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("label_name", models.CharField(max_length=50)),
                (
                    "plan_visual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.planvisual",
                    ),
                ),
                (
                    "plotable_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.plotablestyle",
                    ),
                ),
            ],
        ),
    ]
