# Generated by Django 4.2.1 on 2023-08-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0032_planactivity_milestone_flag"),
    ]

    operations = [
        migrations.RemoveField(model_name="planactivity", name="duration",),
    ]
