# Generated by Django 4.2.1 on 2023-08-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0039_remove_plan_unique_filename_for_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planactivity",
            name="milestone_flag",
            field=models.BooleanField(default=False),
        ),
    ]
