# Generated by Django 4.2.1 on 2023-08-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visual_django",
            "0047_alter_color_name_color_unique_color_name_for_user",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="plotablestyle",
            constraint=models.UniqueConstraint(
                fields=("user", "style_name"), name="unique-style-name-for-user"
            ),
        ),
    ]
