# Generated by Django 5.1.1 on 2024-09-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0065_alter_planfield_field_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planmappedfield",
            name="mapped_field",
            field=models.CharField(
                choices=[
                    ("STICKY_UID", "STICKY_UID"),
                    ("NAME", "NAME"),
                    ("MILESTONE_FLAG", "MILESTONE_FLAG"),
                    ("DURATION", "DURATION"),
                    ("START", "START"),
                    ("END", "END"),
                    ("LEVEL", "LEVEL"),
                ],
                max_length=50,
            ),
        ),
    ]
