# Generated by Django 5.1.1 on 2024-10-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visual_django",
            "0074_rename_timeline_height_planvisual_default_timeline_height",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="planvisual",
            name="default_timeline_plotable_style",
            field=models.ForeignKey(
                default=41,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_timeline_plotable_style",
                to="plan_visual_django.plotablestyle",
            ),
            preserve_default=False,
        ),
    ]
