# Generated by Django 5.1.1 on 2024-10-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visual_django",
            "0076_remove_planvisual_default_timeline_plotable_style_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="timelineforvisual",
            old_name="plotable_style",
            new_name="plotable_style_odd",
        ),
    ]
