# Generated by Django 5.1.1 on 2024-10-13 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0078_timelineforvisual_plotable_style_even_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineforvisual",
            name="plotable_style_even",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plotable_style_even",
                to="plan_visual_django.plotablestyle",
            ),
        ),
    ]
