# Generated by Django 4.1.7 on 2023-02-26 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("red", models.IntegerField(default=0)),
                ("green", models.IntegerField(default=0)),
                ("blue", models.IntegerField(default=0)),
                ("alpha", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FileType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_type_name", models.CharField(max_length=50)),
                ("file_type_description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Font",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("font_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file_name", models.CharField(max_length=100)),
                ("file", models.FileField(null=True, upload_to="plan_files")),
                (
                    "file_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.filetype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=50)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("INT", "Integer"),
                            ("FLOAT", "Decimal number"),
                            ("STR", "String"),
                            (
                                "STR_nnd",
                                "String of form nnd where nn is an integer value",
                            ),
                            ("DATE", "Date (without time)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_description", models.TextField(max_length=1000)),
                ("required_flag", models.BooleanField(default=True)),
                ("sort_index", models.IntegerField()),
            ],
            options={"ordering": ("sort_index",),},
        ),
        migrations.CreateModel(
            name="PlanFieldMappingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="PlanVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("width", models.FloatField(default=30)),
                ("max_height", models.FloatField(default=20)),
                ("include_title", models.BooleanField(default=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlotableShape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlotableShapeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PlotableStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("style_name", models.CharField(max_length=100)),
                ("line_thickness", models.IntegerField()),
                (
                    "fill_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plotablestyle_fill",
                        to="plan_visual_django.color",
                    ),
                ),
                (
                    "font",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="plan_visual_django.font",
                    ),
                ),
                (
                    "line_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plotablestyle_line",
                        to="plan_visual_django.color",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SwimlaneForVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("swim_lane_name", models.CharField(max_length=50)),
                (
                    "plan_visual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.planvisual",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisualActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id_from_plan", models.CharField(max_length=50)),
                (
                    "vertical_positioning_type",
                    models.CharField(
                        choices=[
                            ("TRACK", "Specify track #"),
                            (
                                "REL_TRACK",
                                "Specify relative to last positioned activity",
                            ),
                            ("AUTO", "Automatic positioning"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vertical_positioning_value", models.FloatField()),
                ("height_in_tracks", models.FloatField(default=1)),
                (
                    "text_horizontal_alignment",
                    models.CharField(
                        choices=[
                            ("LEFT", "Left"),
                            ("CENTER", "Center"),
                            ("RIGHT", "Right"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "text_vertical_alignment",
                    models.CharField(
                        choices=[
                            ("TOP", "Top"),
                            ("MIDDLE", "Middle"),
                            ("BOTTOM", "Bottom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "text_flow",
                    models.CharField(
                        choices=[
                            ("LFLOW", "Align right, flow to left"),
                            ("RFLOW", "Align left, flow to right"),
                            ("WSHAPE", "Align centre, flow left/right"),
                            ("CLIPPED", "Align centre, clipped to shape"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "plotable_shape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.plotableshape",
                    ),
                ),
                (
                    "plotable_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.plotablestyle",
                    ),
                ),
                (
                    "swimlane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.swimlaneforvisual",
                    ),
                ),
                (
                    "visual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.planvisual",
                    ),
                ),
            ],
            options={"verbose_name_plural": "visual activities",},
        ),
        migrations.CreateModel(
            name="PlotableShapeAttributesRectangle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                (
                    "plotable_shape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.plotableshape",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlotableShapeAttributesDiamond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                (
                    "plotable_shape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.plotableshape",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plotableshape",
            name="shape_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visual_django.plotableshapetype",
            ),
        ),
        migrations.CreateModel(
            name="PlanMappedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_field_name", models.CharField(max_length=50)),
                (
                    "input_field_type",
                    models.CharField(
                        choices=[
                            ("INT", "Integer"),
                            ("FLOAT", "Decimal number"),
                            ("STR", "String"),
                            (
                                "STR_nnd",
                                "String of form nnd where nn is an integer value",
                            ),
                            ("DATE", "Date (without time)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mapped_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.planfield",
                    ),
                ),
                (
                    "plan_field_mapping_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan_visual_django.planfieldmappingtype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="filetype",
            name="plan_field_mapping_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visual_django.planfieldmappingtype",
            ),
        ),
        migrations.AddConstraint(
            model_name="color",
            constraint=models.CheckConstraint(
                check=models.Q(("red__gte", 0), ("red__lte", 255)),
                name="Red component must be between 0 and 255 (inclusive)",
            ),
        ),
        migrations.AddConstraint(
            model_name="color",
            constraint=models.CheckConstraint(
                check=models.Q(("green__gte", 0), ("green__lte", 255)),
                name="Green component must be between 0 and 255 (inclusive)",
            ),
        ),
        migrations.AddConstraint(
            model_name="color",
            constraint=models.CheckConstraint(
                check=models.Q(("blue__gte", 0), ("blue__lte", 255)),
                name="Blue component must be between 0 and 255 (inclusive)",
            ),
        ),
        migrations.AddConstraint(
            model_name="color",
            constraint=models.CheckConstraint(
                check=models.Q(("alpha__gte", 0), ("alpha__lte", 1)),
                name="Alpha value must be between 0 and 1",
            ),
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                fields=("user", "original_file_name"), name="unique_filename_for_user"
            ),
        ),
    ]
