# Generated by Django 4.2.1 on 2023-08-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0031_alter_planfield_field_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planactivity",
            name="milestone_flag",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
