# Generated by Django 4.2.1 on 2023-08-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0035_alter_planfield_field_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="plan_name",
            field=models.CharField(default="(undefined)", max_length=100),
            preserve_default=False,
        ),
    ]
