# Generated by Django 4.2.1 on 2023-08-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0043_timelineforvisual_timeline_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotablestyle",
            name="font_size",
            field=models.IntegerField(default=10),
        ),
    ]
