# Generated by Django 4.2.1 on 2023-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0048_plotablestyle_unique_style_name_for_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotableshape",
            name="name",
            field=models.CharField(default="(name)", max_length=50),
            preserve_default=False,
        ),
    ]
