# Generated by Django 4.2.1 on 2023-10-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0051_alter_plotableshape_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="color", options={"ordering": ["user", "name"]},
        ),
    ]
