# Generated by Django 5.1.1 on 2024-10-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0066_alter_planmappedfield_mapped_field"),
    ]

    operations = [
        migrations.DeleteModel(name="PlanField",),
    ]
