# Generated by Django 5.1.1 on 2024-10-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0067_delete_planfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("excel-01-msp-export-default-01", "(MSP Export Description)"),
                    (
                        "excel-02-smartsheet-export-01",
                        "Smartsheet Export Format 1 Description)",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
