# Generated by Django 5.1.1 on 2024-10-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0068_alter_plan_file_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan", old_name="file_type", new_name="file_type_name",
        ),
    ]
