# Generated by Django 5.1.1 on 2024-10-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0069_rename_file_type_plan_file_type_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan", old_name="file_type_name", new_name="file_type",
        ),
    ]
