# Generated by Django 5.1.1 on 2024-10-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0073_planvisual_timeline_height"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planvisual",
            old_name="timeline_height",
            new_name="default_timeline_height",
        ),
    ]
