# Generated by Django 5.1.1 on 2024-10-13 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visual_django",
            "0077_rename_plotable_style_timelineforvisual_plotable_style_odd",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineforvisual",
            name="plotable_style_even",
            field=models.ForeignKey(
                default=42,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plotable_style_even",
                to="plan_visual_django.plotablestyle",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="timelineforvisual",
            name="plotable_style_odd",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plotable_style_odd",
                to="plan_visual_django.plotablestyle",
            ),
        ),
    ]
