# Generated by Django 5.1.1 on 2025-02-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0005_helptext"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticcontent",
            name="slug",
            field=models.SlugField(default="xxx", unique=True),
            preserve_default=False,
        ),
    ]
