# Generated by Django 4.1.7 on 2023-03-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0005_alter_planfield_field_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_sticky_activity_id", models.CharField(max_length=50)),
                ("activity_name", models.CharField(max_length=200)),
                ("duration", models.IntegerField()),
                ("end_date", models.DateField()),
            ],
        ),
    ]
