# Generated by Django 4.1.7 on 2023-03-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0006_planactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="planactivity",
            name="level",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planactivity",
            name="start_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
