# Generated by Django 5.1.6 on 2025-03-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0006_staticcontent_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visualactivity",
            options={"ordering": ["pk"], "verbose_name_plural": "visual activities"},
        ),
    ]
