# Generated by Django 5.1.6 on 2025-03-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0007_alter_visualactivity_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="plotableshape", name="shape_type",),
        migrations.RemoveField(
            model_name="plotableshapeattributesrectangle", name="plotable_shape",
        ),
        migrations.AlterField(
            model_name="planvisual",
            name="default_activity_shape",
            field=models.CharField(
                choices=[
                    ("RECTANGLE", "Rectangle"),
                    ("ROUNDED_RECTANGLE", "Rounded Rectangle"),
                    ("BULLET", "Bullet"),
                    ("DIAMOND", "Diamond"),
                    ("ISOSCELES", "Isosceles Triangle"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="visualactivity",
            name="plotable_shape",
            field=models.CharField(
                choices=[
                    ("RECTANGLE", "Rectangle"),
                    ("ROUNDED_RECTANGLE", "Rounded Rectangle"),
                    ("BULLET", "Bullet"),
                    ("DIAMOND", "Diamond"),
                    ("ISOSCELES", "Isosceles Triangle"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="planvisual",
            name="default_milestone_shape",
            field=models.CharField(
                choices=[
                    ("RECTANGLE", "Rectangle"),
                    ("ROUNDED_RECTANGLE", "Rounded Rectangle"),
                    ("BULLET", "Bullet"),
                    ("DIAMOND", "Diamond"),
                    ("ISOSCELES", "Isosceles Triangle"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(name="PlotableShapeAttributesDiamond",),
        migrations.DeleteModel(name="PlotableShapeAttributesRectangle",),
        migrations.DeleteModel(name="PlotableShape",),
    ]
