# Generated by Django 4.1.7 on 2023-03-27 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0007_planactivity_level_planactivity_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="planactivity",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan_visual_django.plan",
            ),
            preserve_default=False,
        ),
    ]
