# Generated by Django 5.1.6 on 2025-03-28 10:27

import plan_visual_django.services.visual.model.plotable_shapes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0008_remove_plotableshape_shape_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planvisual",
            name="default_activity_shape",
            field=models.CharField(
                choices=plan_visual_django.services.visual.model.plotable_shapes.PlotableShapeName.choices,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="planvisual",
            name="default_milestone_shape",
            field=models.CharField(
                choices=plan_visual_django.services.visual.model.plotable_shapes.PlotableShapeName.choices,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="visualactivity",
            name="plotable_shape",
            field=models.CharField(
                choices=plan_visual_django.services.visual.model.plotable_shapes.PlotableShapeName.choices,
                max_length=50,
            ),
        ),
    ]
