# Generated by Django 5.1.6 on 2025-03-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0009_alter_planvisual_default_activity_shape_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="PlotableShapeType",),
    ]
