# Generated by Django 4.1.7 on 2023-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0009_alter_swimlaneforvisual_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualactivity",
            name="enabled",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
