# Generated by Django 4.1.7 on 2023-04-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0010_visualactivity_enabled"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="visualactivity", unique_together={("visual", "unique_id_from_plan")},
        ),
    ]
