# Generated by Django 5.1.6 on 2025-04-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0010_delete_plotableshapetype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planactivity",
            options={
                "ordering": ["plan", "sequence_number"],
                "verbose_name_plural": " Plan activities",
            },
        ),
        migrations.AddField(
            model_name="planactivity",
            name="sequence_number",
            field=models.IntegerField(default=0),
        ),
    ]
