# Generated by Django 5.2.4 on 2025-08-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0011_alter_planactivity_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="file_type_name",
            field=models.CharField(
                choices=[
                    ("excel-01-msp-export-default-01", "Excel - Default MSP Export"),
                    (
                        "excel-02-smartsheet-export-01",
                        "Excel - Default Smartsheet Export (with Id)",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
