# Generated by Django 5.2.4 on 2025-09-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0012_alter_plan_file_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="planvisual",
            name="timeline_gap",
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name="planvisual",
            name="timeline_to_swimlane_gap",
            field=models.FloatField(default=10),
        ),
    ]
