# Generated by Django 5.2.4 on 2025-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0013_planvisual_timeline_gap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planvisual",
            name="activity_date_toggle",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planvisual",
            name="milestone_date_toggle",
            field=models.BooleanField(default=False),
        ),
    ]
