# Generated by Django 5.2.4 on 2025-10-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0014_planvisual_activity_date_toggle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="visual_count",
            field=models.IntegerField(default=0),
        ),
    ]
