# Generated by Django 4.1.7 on 2023-06-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0014_alter_planfield_field_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swimlaneforvisual",
            name="swim_lane_name",
            field=models.CharField(max_length=51),
        ),
    ]
