# Generated by Django 5.2.4 on 2025-10-11 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0015_plan_visual_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staticcontent", options={"ordering": ["parent", "order", "title"]},
        ),
        migrations.AddField(
            model_name="staticcontent",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staticcontent",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="plan_visual_django.staticcontent",
            ),
        ),
    ]
