# Generated by Django 5.2.4 on 2026-03-26 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visual_django",
            "0016_alter_staticcontent_options_staticcontent_order_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousUserProxy",
            fields=[],
            options={
                "verbose_name": "Anonymous User",
                "verbose_name_plural": "Anonymous Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("plan_visual_django.plan",),
        ),
        migrations.AlterModelOptions(
            name="staticcontent", options={"ordering": ["order", "title"]},
        ),
        migrations.CreateModel(
            name="PhysicalPlanFile",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "physical_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "file_name_database",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("plan_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "file_type_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("plan_id", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Physical Plan File",
                "verbose_name_plural": "Physical Plan Files",
                "managed": True,
            },
        ),
    ]
