# Generated by Django 4.2.1 on 2023-06-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0016_swimlaneforvisual_sequence_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planactivity", options={"verbose_name_plural": " Plan activities"},
        ),
    ]
