# Generated by Django 4.2.1 on 2023-06-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0019_alter_visualactivity_text_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("INT", "Integer"),
                    ("STR", "String"),
                    ("DATE", "Date (without time)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planmappedfield",
            name="input_field_type",
            field=models.CharField(
                choices=[
                    ("INT", "Integer"),
                    ("FLOAT", "Decimal Number"),
                    ("STR", "String"),
                    ("STR_nnd", "String of form nnd where nn is an integer value"),
                    ("DATE", "Date (without time"),
                ],
                max_length=20,
            ),
        ),
    ]
