# Generated by Django 4.2.1 on 2023-07-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visual_django",
            "0024_alter_plotableshapetype_name_timelinelabelsforvisual",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TimelineLabelsForVisual", new_name="TimelineForVisual",
        ),
        migrations.AlterField(
            model_name="plotableshapetype",
            name="name",
            field=models.CharField(
                choices=[
                    ("RECTANGLE", "Rectangle"),
                    ("ROUNDED_RECTANGLE", "Rectangle"),
                    ("DIAMOND", "Diamond"),
                    ("ISOSCELES", "Isosceles Triangle"),
                ],
                max_length=20,
            ),
        ),
    ]
