# Generated by Django 4.2.1 on 2023-07-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visual_django",
            "0026_rename_label_name_timelineforvisual_timeline_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="planmappedfield",
            name="input_field_type",
            field=models.CharField(
                choices=[
                    ("INT", "Integer"),
                    ("FLOAT", "Decimal Number"),
                    ("STR", "String"),
                    ("STR_OR_INT", "String or integer"),
                    ("STR_nnd", "String of form nnd where nn is an integer value"),
                    (
                        "STR_nndays",
                        "String of form nn Days(?) where nn is an integer value. ? is optional",
                    ),
                    ("STR_DATE_DMY", "String of form dd MMMMM YYYY"),
                    ("DATE", "Date (without time)"),
                ],
                max_length=20,
            ),
        ),
    ]
