# Generated by Django 4.2.1 on 2023-08-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0033_remove_planactivity_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planfield",
            name="field_name",
            field=models.CharField(
                choices=[
                    ("unique_sticky_activity_id", "Unique id for activity"),
                    ("activity_name", "Name of activity"),
                    (
                        "duration",
                        "Work effort for activity - not stored, used to work out whether this is a milestone",
                    ),
                    ("milestone", "Duration of activity"),
                    ("start_date", "Start date of activity"),
                    ("end_date", "End date of activity"),
                    ("level", "The level in the hierarchy of the an activity"),
                ],
                help_text="field name used in common datastructure for plan",
                max_length=50,
            ),
        ),
    ]
