# Generated by Django 4.2.1 on 2023-08-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0037_rename_original_file_name_plan_file_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="plan", name="unique_filename_for_user",
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                fields=("user", "file_name"), name="unique_filename_for_user"
            ),
        ),
    ]
