# Generated by Django 4.2.1 on 2023-08-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0038_remove_plan_unique_filename_for_user_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="plan", name="unique_filename_for_user",
        ),
        migrations.AddConstraint(
            model_name="plan",
            constraint=models.UniqueConstraint(
                fields=("user", "plan_name"), name="unique_filename_for_user"
            ),
        ),
    ]
