# Generated by Django 4.2.1 on 2023-08-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visual_django",
            "0041_planvisual_default_activity_plotable_style_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="planvisual",
            name="milestone_width",
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name="planvisual",
            name="swimlane_gap",
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name="planvisual",
            name="track_gap",
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name="planvisual",
            name="track_height",
            field=models.FloatField(default=20),
        ),
    ]
