# Generated by Django 4.2.1 on 2023-08-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_visual_django",
            "0042_planvisual_milestone_width_planvisual_swimlane_gap_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineforvisual",
            name="timeline_height",
            field=models.FloatField(default=10),
        ),
    ]
