# Generated by Django 4.2.1 on 2023-08-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0046_plotablestyle_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color", name="name", field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="color",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique-color-name-for-user"
            ),
        ),
    ]
