# Generated by Django 4.2.1 on 2023-10-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0052_alter_color_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plotablestyle", options={"ordering": ["user", "style_name"]},
        ),
    ]
