# Generated by Django 5.0 on 2024-03-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0055_alter_planmappedfield_input_field_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="swimlaneforvisual",
            unique_together={
                ("plan_visual", "sequence_number"),
                ("plan_visual", "swim_lane_name"),
            },
        ),
    ]
