# Generated by Django 5.0.4 on 2024-09-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0059_staticcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filetype",
            name="file_type_description",
            field=models.TextField(max_length=1000),
        ),
    ]
