# Generated by Django 5.1.1 on 2024-09-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0062_alter_plotableshape_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelineforvisual",
            name="timeline_type",
            field=models.CharField(
                choices=[
                    ("MONTHS", "One label for each month"),
                    (
                        "QUARTERS",
                        "One label for each sequence of three months, variable start",
                    ),
                    (
                        "HALF_YEAR",
                        "One label for each sequence of six months, start on Jan or Jul",
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
