# Generated by Django 5.1.1 on 2024-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0063_alter_timelineforvisual_timeline_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planfield",
            name="field_name",
            field=models.CharField(
                choices=[
                    ("unique_sticky_activity_id", "Unique id for activity"),
                    ("activity_name", "Name of activity"),
                    ("milestone_flag", "Is this activity a milestone"),
                    ("start_date", "Start date of activity"),
                    ("end_date", "End date of activity"),
                    ("level", "The level in the hierarchy of the an activity"),
                ],
                help_text="field name used in common datastructure for plan",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="timelineforvisual",
            name="timeline_type",
            field=models.CharField(
                choices=[
                    ("MONTHS", "One label for each month"),
                    (
                        "QUARTERS",
                        "One label for each sequence of three months, variable start",
                    ),
                    (
                        "HALF_YEAR",
                        "One label for each sequence of six months, start on Jan or Jul",
                    ),
                    (
                        "YEAR",
                        "One label for each year covered by the plan, start at Jan",
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
