# Generated by Django 5.1.1 on 2024-09-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0064_alter_planfield_field_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planfield",
            name="field_name",
            field=models.CharField(
                choices=[
                    ("unique_sticky_activity_id", "Unique id for activity"),
                    ("activity_name", "Name of activity"),
                    (
                        "duration",
                        "Work effort for activity (not stored, used to work out whether this is a milestone)",
                    ),
                    ("milestone_flag", "Is this activity a milestone"),
                    ("start_date", "Start date of activity"),
                    ("end_date", "End date of activity"),
                    ("level", "The level in the hierarchy of the an activity"),
                ],
                help_text="field name used in common datastructure for plan",
                max_length=50,
            ),
        ),
    ]
