# Generated by Django 5.1.1 on 2024-10-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0071_rename_file_type_plan_file_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planmappedfield", name="plan_field_mapping_type",
        ),
        migrations.AlterField(
            model_name="plan",
            name="file_type_name",
            field=models.CharField(
                choices=[
                    (
                        "excel-01-msp-export-default-01",
                        "Represents mapping of all field names from Microsoft Project export to Excel, using \n        default field names.\n        ",
                    ),
                    (
                        "excel-02-smartsheet-export-01",
                        "Represents one of several field mappings from a Smartsheet export to Excel.  Note that Smartsheet\n        doesn't have build-in columns for ID or Level, so there are no default names.",
                    ),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planactivity",
            unique_together={("plan", "unique_sticky_activity_id")},
        ),
        migrations.DeleteModel(name="FileType",),
        migrations.DeleteModel(name="PlanFieldMappingType",),
        migrations.DeleteModel(name="PlanMappedField",),
    ]
