# Generated by Django 5.1.1 on 2024-10-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0075_planvisual_default_timeline_plotable_style"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planvisual", name="default_timeline_plotable_style",
        ),
        migrations.AddField(
            model_name="planvisual",
            name="default_timeline_plotable_style_even",
            field=models.ForeignKey(
                default=42,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_timeline_plotable_style_even",
                to="plan_visual_django.plotablestyle",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planvisual",
            name="default_timeline_plotable_style_odd",
            field=models.ForeignKey(
                default=41,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_timeline_plotable_style_odd",
                to="plan_visual_django.plotablestyle",
            ),
            preserve_default=False,
        ),
    ]
