# Generated by Django 5.1.1 on 2024-10-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_visual_django", "0079_alter_timelineforvisual_plotable_style_even"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planvisual",
            name="default_timeline_plotable_style_even",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_timeline_plotable_style_even",
                to="plan_visual_django.plotablestyle",
            ),
        ),
    ]
