name: Build Docker images and push to Digital Ocean Repository

on:
  workflow_call:
    secrets:
      SECRET_DO_DOCKER_REGISTRY_API_TOKEN:
        required: true
      SECRET_DO_DOCKER_REGISTRY_NAME:
        required: true
jobs:
  build_and_push_docker_images:
    runs-on: ubuntu-latest
    steps:
    # Checks out the repository code to the runner
    - name: Checkout Development or master branch
      uses: actions/checkout@v3

    # Installs the Digital Ocean CLI tool for interacting with DO services
    - name: Install Digital Ocean command line - doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.SECRET_DO_DOCKER_REGISTRY_API_TOKEN }}

    # Builds the Nginx Docker image using the specified Dockerfile
    - name: Build Docker image for Nginx
      run: docker build
        --file ./devops/docker/nginx/Dockerfile
        --tag ${{ secrets.SECRET_DO_DOCKER_REGISTRY_NAME }}/plan-visualiser-nginx:$(echo $GITHUB_SHA | head -c7)
        .

    # Builds the Gunicorn Docker image using the specified Dockerfile
    - name: Build Docker image for Gunicorn
      run: docker build
        --file ./devops/docker/gunicorn/Dockerfile
        --tag ${{ secrets.SECRET_DO_DOCKER_REGISTRY_NAME }}/plan-visualiser-django_gunicorn:$(echo $GITHUB_SHA | head -c7)
        .

    # Authenticates with the DigitalOcean Container Registry using temporary credentials
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    # Uploads the built Nginx image to the DigitalOcean Container Registry
    - name: Push Nginx image to DigitalOcean Container Registry
      run: docker push ${{ secrets.SECRET_DO_DOCKER_REGISTRY_NAME }}/plan-visualiser-nginx:$(echo $GITHUB_SHA | head -c7)

    # Uploads the built Gunicorn image to the DigitalOcean Container Registry
    - name: Push Gunicorn image to DigitalOcean Container Registry
      run: docker push ${{ secrets.SECRET_DO_DOCKER_REGISTRY_NAME }}/plan-visualiser-django_gunicorn:$(echo $GITHUB_SHA | head -c7)
