name: Common Deployment Workflow

on:
  workflow_call:
    inputs:
      branch:
        description: Branch being deployed (e.g., development, main)
        required: true
        type: string
      environment:
        description: Deployment environment (e.g., staging, live)
        required: true
        type: string
      python_version:
        description: Python version
        required: true
        type: string
    secrets:
      SECRET_STAGING_DATABASE_URL:
        required: true
      SECRET_STAGING_DOCKER_REGISTRY_API_TOKEN:
        required: true
      SECRET_STAGING_DOCKER_REGISTRY_NAME:
        required: true
      SECRET_DO_STAGING_DROPLET_SSH_PRIVATE_KEY:
        required: true
      SECRET_DO_DROPLET_STAGING_HOST_IP:
        required: true
      SECRET_POSTGRES_DB_NAME:
        required: true
      SECRET_POSTGRES_USER:
        required: true
      SECRET_POSTGRES_PASSWORD:
        required: true
      SECRET_DJANGO_SECRET_KEY:
        required: true
      SECRET_DO_DOCKER_REGISTRY_NAME:
        required: true
      SECRET_DO_DOCKER_REGISTRY_API_TOKEN:
        required: true

jobs:
  pre-deploy-test:
    uses: ./.github/workflows/_common-test.yml
    with:
      python_version: ${{ inputs.python_version }}
      environment: ${{ inputs.environment }}

  deploy:
    needs: [pre-deploy-test]
    runs-on: ubuntu-latest
    steps:
      # Existing deployment steps
      - name: Checkout ${{ inputs.branch }}
        uses: actions/checkout@v3

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SECRET_DO_STAGING_DROPLET_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SECRET_DO_DROPLET_STAGING_HOST_IP }}" > ~/.ssh/known_hosts

      - name: Connect and pull Docker images on droplet
        run: |
          chmod +x ./deploy_on_remote.sh  # Note this is on the runner - not the live server!!
          ssh -o StrictHostKeyChecking=no root@"${{ secrets.SECRET_DO_DROPLET_STAGING_HOST_IP }}" 'bash -s' -- "${{ secrets.SECRET_POSTGRES_DB_NAME }}" "${{ secrets.SECRET_POSTGRES_USER }}" "${{ secrets.SECRET_POSTGRES_PASSWORD }}" "${{ secrets.SECRET_DJANGO_SECRET_KEY }}" $(echo $GITHUB_SHA | head -c7) staging "${{ secrets.SECRET_DO_DOCKER_REGISTRY_NAME }}" "${{ secrets.SECRET_DO_DOCKER_REGISTRY_API_TOKEN }}" < ./deploy_on_remote.sh

      - name: Clean up SSH keys
        run: rm -rf ~/.ssh
