name: Common Deployment Workflow

on:
  workflow_call:
    inputs:
      branch:
        description: Branch being deployed (e.g., development, main)
        required: true
        type: string
      environment:
        description: Deployment environment (e.g., staging, live)
        required: true
        type: string
      python_version:
        description: Python version
        required: true
        type: string
    secrets:
      SECRET_DO_DROPLET_SSH_PRIVATE_KEY:
        required: true
      SECRET_DO_DROPLET_HOST_IP:
        required: true
      SECRET_POSTGRES_DB_NAME:
        required: true
      SECRET_POSTGRES_USER:
        required: true
      SECRET_POSTGRES_PASSWORD:
        required: true
      SECRET_DJANGO_SECRET_KEY:
        required: true
      SECRET_DO_DOCKER_REGISTRY_NAME:
        required: true
      SECRET_DO_DOCKER_REGISTRY_API_TOKEN:
        required: true

jobs:
  pre-deploy-test:
    uses: ./.github/workflows/_common-test.yml
    with:
      python_version: ${{ inputs.python_version }}
      environment: ${{ inputs.environment }}

  build-and-push:
    needs: [ pre-deploy-test ]
    if: inputs.environment != 'production'
    uses: ./.github/workflows/_build-and-push.yml
    secrets: inherit

  pull-and-deploy:
    needs: [ pre-deploy-test, build-and-push ]
    if: |
      always() &&
      needs.pre-deploy-test.result == 'success' &&
      (
        (inputs.environment == 'production') ||
        (inputs.environment != 'production' && needs.build-and-push.result == 'success')
      )
    uses: ./.github/workflows/_common-pull-and-deploy.yml
    with:
      python_version: ${{ inputs.python_version }}
      environment: ${{ inputs.environment }}

    secrets: inherit
