name: Build Docker images and push to Digital Ocean Repository

on:
  workflow_call:
    inputs:
      python_version:
        description: Python version
        required: true
        type: string
    secrets:
      SECRET_DO_DOCKER_REGISTRY_API_TOKEN:
        required: true
      SECRET_DO_DOCKER_REGISTRY_NAME:
        required: true
jobs:
  build_and_push_docker_images:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "${{ inputs.python_version }}" ]
    steps:
    - name: Checkout Development or master branch
      uses: actions/checkout@v3

    - name: Install Digital Ocean command line - doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.SECRET_DO_DOCKER_REGISTRY_API_TOKEN }}

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image for Nginx
      run: docker build
        --file ./devops/docker/nginx/Dockerfile
        --tag ${{ secrets.SECRET_DO_DOCKER_REGISTRY_NAME }}/plan_visualiser_2023_02-nginx:$(echo $GITHUB_SHA | head -c7)
        .

    - name: Build Docker image for Gunicorn
      run: docker build
        --file ./devops/docker/gunicorn/Dockerfile
        --tag ${{ secrets.SECRET_DO_DOCKER_REGISTRY_NAME }}/plan_visualiser_2023_02-django_gunicorn:$(echo $GITHUB_SHA | head -c7)
        .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push Nginx image to DigitalOcean Container Registry
      run: docker push ${{ secrets.SECRET_DO_DOCKER_REGISTRY_NAME }}/plan_visualiser_2023_02-nginx:$(echo $GITHUB_SHA | head -c7)

    - name: Push Gunicorn image to DigitalOcean Container Registry
      run: docker push ${{ secrets.SECRET_DO_DOCKER_REGISTRY_NAME }}/plan_visualiser_2023_02-django_gunicorn:$(echo $GITHUB_SHA | head -c7)
