name: Deploy to Staging from Development

on:
  push:
    branches:
      - Development
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_common-deploy.yml
    with:
      branch: Development
      environment: staging
      python_version: "3.12"
    secrets:
      # Declare secrets used in _common-deploy.yml (but standardise name for common processing)

      # Non environment specific secrets...
      SECRET_DO_DOCKER_REGISTRY_NAME: ${{ secrets.DO_DOCKER_REGISTRY_NAME }}
      SECRET_POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
      SECRET_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      SECRET_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SECRET_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      SECRET_DO_DOCKER_REGISTRY_API_TOKEN: ${{ secrets.DO_DOCKER_REGISTRY_API_TOKEN }}
      INITIAL_USER_EMAIL_DOMAIN: ${{ secrets.INITIAL_USER_EMAIL_DOMAIN }}
      # Environment specific secrets...
      SECRET_DO_DROPLET_SSH_PRIVATE_KEY: ${{ secrets.DO_STAGING_DROPLET_SSH_PRIVATE_KEY }}
      SECRET_DO_DROPLET_HOST_IP: ${{ secrets.DO_DROPLET_STAGING_HOST_IP }}

      SECRET_APP_USER_1_NAME: ${{ secrets.STAGING_APP_USER_1_NAME }}
      SECRET_APP_USER_1_PASSWORD: ${{ secrets.STAGING_APP_USER_1_PASSWORD }}
      SECRET_ADMIN_NAME: ${{ secrets.STAGING_ADMIN_NAME }}
      SECRET_ADMIN_PASSWORD: ${{ secrets.STAGING_ADMIN_PASSWORD }}
      SECRET_SHARED_USER_NAME: ${{ secrets.STAGING_SHARED_USER_NAME }}
      SECRET_SHARED_USER_PASSWORD: ${{ secrets.STAGING_SHARED_USER_PASSWORD }}

      SECRET_EMAIL_HOST: ${{ secrets.STAGING_EMAIL_HOST }}
      SECRET_EMAIL_USE_SSL: ${{ secrets.STAGING_EMAIL_USE_SSL }}
      SECRET_EMAIL_HOST_USER: ${{ secrets.STAGING_EMAIL_HOST_USER }}
      SECRET_EMAIL_HOST_PASSWORD: ${{ secrets.STAGING_EMAIL_HOST_PASSWORD }}
      SECRET_EMAIL_PORT: ${{ secrets.STAGING_EMAIL_PORT }}
