name: Deploy to Live

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/common/_common-deploy.yml
    with:
      branch: main
      environment: live
      python_version: "3.12"
    secrets:
      DATABASE_URL: ${{ secrets.LIVE_DATABASE_URL }}
      DOCKER_REGISTRY_API_TOKEN: ${{ secrets.LIVE_DOCKER_REGISTRY_API_TOKEN }}
      DOCKER_REGISTRY_NAME: ${{ secrets.LIVE_DOCKER_REGISTRY_NAME }}
      SSH_PRIVATE_KEY: ${{ secrets.LIVE_SSH_PRIVATE_KEY }}
      SERVER_HOST_IP: ${{ secrets.LIVE_SERVER_HOST_IP }}