name: Deploy from Development branch to Staging server

on:
  push:
    branches: [ "Development" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Deploy to Staging'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - name: Checkout Development branch
      uses: actions/checkout@v3

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_DOCKER_REGISTRY_API_TOKEN }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Build a Docker image of your application in your registry and tag the image with the $GITHUB_SHA.
    - name: Build Docker image for Nginx
      run: docker build -t $(echo $REGISTRY)/plan_visualiser_2023_02-nginx:$(echo $GITHUB_SHA | head -c7) .

    - name: Build Docker image for Gunicorn
      run: docker build -t $(echo $REGISTRY)/plan_visualiser_2023_02-django_gunicorn:$(echo $GITHUB_SHA | head -c7) .

    - name: Build Docker image for Postgres
      run: docker build -t $(echo $REGISTRY)/postgres:$(echo $GITHUB_SHA | head -c7) .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push Nginx image to DigitalOcean Container Registry
      run: docker push ${{ secrets.DO_DOCKER_REGISTRY_NAME }}/plan_visualiser_2023_02-nginx:$(echo $GITHUB_SHA | head -c7)

    - name: Push Gunicorn image to DigitalOcean Container Registry
      run: docker push ${{ secrets.DO_DOCKER_REGISTRY_NAME }}/plan_visualiser_2023_02-django_gunicorn:$(echo $GITHUB_SHA | head -c7)

    - name: Push Postgres image to DigitalOcean Container Registry
      run: docker push ${{ secrets.DO_DOCKER_REGISTRY_NAME }}/postgres:$(echo $GITHUB_SHA | head -c7)

    - name: Run Tests (Development)
      run: |
        python manage.py test
